### ISSUE TITLE
Quick overview shows internal ID on reload

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-frontend#111]
When reloading the page, the quick overview on mobile shows the internal SudoSOS id

**Comment by JustSamuel** [comment]
Token always contains a `UserResponse` and never a `GewisUserResponse` , therefore on refresh the website defaults to the provided token info and thus sees the user as a external user since its lacking a GewisId.

solutions:
Make the token contain a GewisUserResponse (backend issue)
On refresh do a user/me call to update store

**Comment by JustSamuel** [comment]
Pushed a temp fix which updates the currentUser after refresh to dev.

**Comment by JustSamuel** [comment]
This is not the preferred solution though, so I say we keep it semi open

**Comment by SuperVK** [comment]
Also this issue is not even fixed.

**Comment by CodeNamedRobin** [comment]
Closed in version 1.0.0
